import { useState } from "react";
import {
  AlertTriangle,
  Briefcase,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Clock,
  Code2,
  Copy,
  Download,
  FileCheck2,
  FileCode2,
  FileText,
  Fingerprint,
  Globe,
  HelpCircle,
  Layers,
  ListChecks,
  Lock,
  Printer,
  Scale,
  Search,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Sparkles,
  UserCheck,
  Users,
  Wrench,
  XCircle,
} from "lucide-react";
import { Link } from "react-router-dom";
import type {
  AuditorSignature,
  ComplianceFinding,
  ManifestArtifact,
  PrivacyPolicyArtifact,
  Project,
  TestCase,
} from "../types/release";
import {
  explainComplianceFindingInLayman,
  explainPermissionInLayman,
  explainPrivacyClauseInLayman,
} from "../lib/laymanExplainer";
import { generateHtmlReport, generateMarkdownReport } from "../lib/exportReport";
import { useAuth } from "../context/AuthContext";
import { notifyToast } from "../lib/alerts";
import { Badge } from "./ui/Badge";
import { Button } from "./ui/Button";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/Card";

type ActiveTab = "issues" | "checklist" | "permissions" | "privacy" | "qa";

export function ReportPage({
  project,
  manifest,
  privacyPolicy,
  complianceFindings,
  testCases,
  auditorSignature,
}: {
  project: Project;
  manifest?: ManifestArtifact;
  privacyPolicy?: PrivacyPolicyArtifact;
  complianceFindings: ComplianceFinding[];
  testCases: TestCase[];
  auditorSignature?: AuditorSignature;
}) {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState<ActiveTab>("issues");
  const [issueFilter, setIssueFilter] = useState<"all" | "blocked" | "warning" | "passed">("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [isExportMenuOpen, setIsExportMenuOpen] = useState(false);
  const [showTechnicalDetails, setShowTechnicalDetails] = useState<Record<string, boolean>>({});

  // Sign-off checklist
  const [checkedSignOffs, setCheckedSignOffs] = useState<Record<string, boolean>>({
    legal: false,
    permissions: false,
    qa: false,
    storeAssets: false,
  });

  const highBlockers = complianceFindings.filter((c) => c.status === "Blocked" || c.severity === "High");
  const warnings = complianceFindings.filter((c) => c.status === "Warning" || (c.severity === "Medium" && c.status !== "Blocked"));
  const passedChecks = complianceFindings.filter((c) => c.status === "Passed");

  const isApproved = highBlockers.length === 0 && project.readinessScore >= 80;

  // Department action item counts
  const departmentCounts: Record<string, number> = {};
  complianceFindings
    .filter((c) => c.status !== "Passed")
    .forEach((c) => {
      const layman = explainComplianceFindingInLayman(c);
      departmentCounts[layman.whoFixesIt] = (departmentCounts[layman.whoFixesIt] || 0) + 1;
    });

  // Filtered issues
  const filteredFindings = complianceFindings.filter((c) => {
    if (issueFilter === "blocked" && c.status !== "Blocked") return false;
    if (issueFilter === "warning" && c.status !== "Warning") return false;
    if (issueFilter === "passed" && c.status !== "Passed") return false;
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      return (
        c.title.toLowerCase().includes(q) ||
        c.detail.toLowerCase().includes(q) ||
        c.owner.toLowerCase().includes(q)
      );
    }
    return true;
  });

  const toggleTechnical = (id: string) => {
    setShowTechnicalDetails((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const handleCopySummary = () => {
    const summary = `
📊 RELEASE READINESS EXECUTIVE SUMMARY
App: ${project.name} (${project.packageId})
Platform: ${project.platform} | Version: ${project.version}
Target Release: ${project.releaseTarget}
Readiness Score: ${project.readinessScore}/100 [${isApproved ? "READY FOR RELEASE" : "SUBMISSION BLOCKED"}]

🚨 Critical Blockers: ${highBlockers.length}
⚠️ Warnings: ${warnings.length}
✅ Passed Checks: ${passedChecks.length}

Department Action Items:
${Object.entries(departmentCounts)
  .map(([dept, count]) => `• ${dept}: ${count} items`)
  .join("\n")}

Generated by ReleaseIQ Pre-Flight Engine
`;
    navigator.clipboard.writeText(summary);
    notifyToast({
      title: "Quick team summary copied to clipboard!",
      icon: "success",
    });
  };

  const handlePrint = () => {
    setIsExportMenuOpen(false);
    window.print();
  };

  const handleExportHtml = () => {
    setIsExportMenuOpen(false);
    const html = generateHtmlReport({
      project,
      manifest,
      privacyPolicy,
      complianceFindings,
      testCases,
      generatedBy: user?.name || "Parv Tiwari",
    });
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${project.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}-readiness-report.html`;
    a.click();
    URL.revokeObjectURL(url);
    notifyToast({
      title: "Interactive HTML Report downloaded!",
      icon: "success",
    });
  };

  const handleExportMarkdown = () => {
    setIsExportMenuOpen(false);
    const md = generateMarkdownReport({
      project,
      manifest,
      privacyPolicy,
      complianceFindings,
      testCases,
      generatedBy: user?.name || "Parv Tiwari",
    });
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${project.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}-readiness-report.md`;
    a.click();
    URL.revokeObjectURL(url);
    notifyToast({
      title: "Markdown Report downloaded!",
      icon: "success",
    });
  };

  const handleExportJson = () => {
    setIsExportMenuOpen(false);
    const reportData = {
      reportType: "ReleaseIQ Release Readiness Audit Certificate",
      generatedAt: new Date().toISOString(),
      auditHash: `AUDIT-${project.id.slice(0, 8).toUpperCase()}-${Date.now().toString(36).toUpperCase()}`,
      project: {
        id: project.id,
        name: project.name,
        packageId: project.packageId,
        version: project.version,
        platform: project.platform,
        category: project.category,
        releaseTarget: project.releaseTarget,
        readinessScore: project.readinessScore,
        status: project.status,
        recommendation: isApproved ? "APPROVED_FOR_SUBMISSION" : "SUBMISSION_BLOCKED",
      },
      manifestAudit: {
        artifactName: manifest?.name || null,
        targetSdkVersion: manifest?.targetSdkVersion ?? 34,
        minSdkVersion: manifest?.minSdkVersion ?? 26,
        permissionsCount: manifest?.permissions.length || 0,
        permissions: manifest?.permissions || [],
      },
      privacyPolicyAudit: {
        documentName: privacyPolicy?.fileName || null,
        clausesEvaluated: privacyPolicy?.clauses.length || 0,
        clauses: privacyPolicy?.clauses || [],
      },
      complianceFindings: complianceFindings.map((cf) => ({
        id: cf.id,
        title: cf.title,
        status: cf.status,
        severity: cf.severity,
        owner: cf.owner,
        detail: cf.detail,
        remediation: cf.remediation || null,
      })),
      qaValidationSuite: {
        totalTestCases: testCases.length,
        passedTests: testCases.filter((tc) => tc.status === "Passed").length,
        blockedTests: testCases.filter((tc) => tc.status === "Blocked").length,
        testCases: testCases,
      },
      auditorDigitalSignOff: auditorSignature || {
        status: "UNSIGNED",
        note: "Auditor sign-off pending in QA Verification Dossier",
      },
    };

    const jsonStr = JSON.stringify(reportData, null, 2);
    const blob = new Blob([jsonStr], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${project.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}-readiness-report.json`;
    a.click();
    URL.revokeObjectURL(url);
    notifyToast({
      title: "JSON Audit Data downloaded!",
      icon: "success",
    });
  };

  return (
    <div className="mx-auto flex max-w-6xl flex-col gap-6 print:m-0 print:p-0">
      {/* PDQA Verification Dossier Banner */}
      <div className="rounded-xl border border-primary/30 bg-gradient-to-r from-primary/15 via-primary/5 to-transparent p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3 print:hidden">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary text-primary-foreground font-bold shrink-0">
            <Fingerprint className="h-5 w-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold uppercase tracking-wider text-primary">PDQA Audit Dossier</span>
              {auditorSignature ? (
                <Badge tone="success" className="text-[10px] px-1.5 py-0">Digitally Certified</Badge>
              ) : (
                <Badge tone="warning" className="text-[10px] px-1.5 py-0">Sign-Off Pending</Badge>
              )}
            </div>
            <p className="text-xs text-foreground font-medium mt-0.5">
              Access the mathematical calculation formulas, XML tag traces, and anti-paste auditor signature box.
            </p>
          </div>
        </div>
        <Link to="/verification" className="shrink-0">
          <Button className="w-full sm:w-auto h-8 text-xs">
            <Scale className="h-4 w-4 mr-1.5" /> Open QA Verification Dossier
          </Button>
        </Link>
      </div>

      {/* Top Controls Header */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between print:hidden">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Pre-Flight Assessment</p>
          <h1 className="text-2xl font-bold text-foreground">Release Readiness Report</h1>
          <p className="text-xs text-muted-foreground mt-0.5">
            Audit evaluation for {project.name} · Target {project.releaseTarget}
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Button variant="secondary" onClick={handleCopySummary} className="h-8 text-xs px-2.5" title="Copy text summary for Slack / Teams">
            <Copy className="h-3.5 w-3.5 mr-1" /> Copy Summary
          </Button>
          <Button variant="secondary" onClick={handlePrint} className="h-8 text-xs px-2.5" title="Print or save as PDF">
            <Printer className="h-3.5 w-3.5 mr-1" /> Print / PDF
          </Button>

          {/* Export Dropdown */}
          <div className="relative">
            <Button
              onClick={() => setIsExportMenuOpen((prev) => !prev)}
              className="h-8 text-xs px-2.5"
            >
              <Download className="h-3.5 w-3.5 mr-1" /> Export Report <ChevronDown className="h-3 w-3 ml-1" />
            </Button>
            {isExportMenuOpen && (
              <div className="absolute right-0 top-full mt-1.5 z-20 w-52 rounded-lg border border-border bg-card p-1.5 shadow-xl text-xs space-y-1">
                <button
                  onClick={handleExportHtml}
                  className="w-full flex items-center gap-2 rounded px-2.5 py-1.5 text-left text-foreground hover:bg-accent cursor-pointer"
                >
                  <Globe className="h-3.5 w-3.5 text-primary shrink-0" />
                  <div>
                    <p className="font-semibold">Interactive HTML</p>
                    <p className="text-[10px] text-muted-foreground">Standalone offline web page</p>
                  </div>
                </button>
                <button
                  onClick={handleExportMarkdown}
                  className="w-full flex items-center gap-2 rounded px-2.5 py-1.5 text-left text-foreground hover:bg-accent cursor-pointer"
                >
                  <FileText className="h-3.5 w-3.5 text-primary shrink-0" />
                  <div>
                    <p className="font-semibold">Markdown (.md)</p>
                    <p className="text-[10px] text-muted-foreground">For GitHub PRs &amp; Jira</p>
                  </div>
                </button>
                <button
                  onClick={handleExportJson}
                  className="w-full flex items-center gap-2 rounded px-2.5 py-1.5 text-left text-foreground hover:bg-accent cursor-pointer"
                >
                  <Code2 className="h-3.5 w-3.5 text-primary shrink-0" />
                  <div>
                    <p className="font-semibold">Machine JSON</p>
                    <p className="text-[10px] text-muted-foreground">For CI/CD automated gates</p>
                  </div>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Executive Verdict Card */}
      <Card className="border-2 border-border print:border-none">
        <CardContent className="p-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div className="space-y-1.5">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-primary/10 text-primary border border-primary/20">
                  {project.platform} Release Certificate
                </span>
                <span className="text-xs font-mono text-muted-foreground">
                  Target SDK: {manifest?.targetSdkVersion ?? (project.platform === "iOS" ? "18" : "34")}
                </span>
              </div>
              <h2 className="text-2xl font-bold text-foreground">{project.name}</h2>
              <p className="text-xs font-mono text-muted-foreground">
                {project.packageId} · Version {project.version} · Target: {project.releaseTarget}
              </p>
            </div>

            {/* Score & Recommendation Banner */}
            <div className="flex items-center gap-5 rounded-xl border border-border bg-accent/40 p-4 shrink-0">
              <div className="text-center">
                <p className="text-[11px] font-semibold uppercase text-muted-foreground">Readiness Score</p>
                <div className="flex items-baseline justify-center gap-1 mt-0.5">
                  <span className="text-4xl font-extrabold text-foreground">{project.readinessScore}</span>
                  <span className="text-xs font-bold text-muted-foreground">/100</span>
                </div>
              </div>
              <div className="h-12 w-px bg-border" />
              <div className="space-y-1">
                <p className="text-[11px] font-semibold uppercase text-muted-foreground">Store Decision</p>
                <Badge tone={isApproved ? "success" : "danger"}>
                  {isApproved ? "Approved for Release" : "Submission Blocked"}
                </Badge>
              </div>
            </div>
          </div>

          {/* Quick Metrics Strip */}
          <div className="mt-5 grid grid-cols-2 sm:grid-cols-4 gap-3 border-t border-border pt-4 text-center">
            <div className="rounded-lg border border-border bg-card p-3">
              <p className="text-[11px] text-muted-foreground">Critical Blockers</p>
              <p className="text-xl font-bold text-rose-600">{highBlockers.length}</p>
            </div>
            <div className="rounded-lg border border-border bg-card p-3">
              <p className="text-[11px] text-muted-foreground">Review Warnings</p>
              <p className="text-xl font-bold text-amber-600">{warnings.length}</p>
            </div>
            <div className="rounded-lg border border-border bg-card p-3">
              <p className="text-[11px] text-muted-foreground">Passed Checks</p>
              <p className="text-xl font-bold text-emerald-600">{passedChecks.length}</p>
            </div>
            <div className="rounded-lg border border-border bg-card p-3">
              <p className="text-[11px] text-muted-foreground">QA Test Cases</p>
              <p className="text-xl font-bold text-primary">{testCases.length}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Tabs Navigation */}
      <div className="flex border-b border-border text-xs font-semibold gap-2 overflow-x-auto print:hidden">
        <button
          onClick={() => setActiveTab("issues")}
          className={`pb-2.5 px-3 border-b-2 cursor-pointer transition ${
            activeTab === "issues" ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"
          }`}
        >
          Compliance Issues ({complianceFindings.length})
        </button>
        <button
          onClick={() => setActiveTab("checklist")}
          className={`pb-2.5 px-3 border-b-2 cursor-pointer transition ${
            activeTab === "checklist" ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"
          }`}
        >
          Pre-Submission Sign-Off Checklist
        </button>
        <button
          onClick={() => setActiveTab("permissions")}
          className={`pb-2.5 px-3 border-b-2 cursor-pointer transition ${
            activeTab === "permissions" ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"
          }`}
        >
          Permissions ({manifest?.permissions.length || 0})
        </button>
        <button
          onClick={() => setActiveTab("privacy")}
          className={`pb-2.5 px-3 border-b-2 cursor-pointer transition ${
            activeTab === "privacy" ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"
          }`}
        >
          Privacy Policy ({privacyPolicy?.clauses.length || 0})
        </button>
        <button
          onClick={() => setActiveTab("qa")}
          className={`pb-2.5 px-3 border-b-2 cursor-pointer transition ${
            activeTab === "qa" ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"
          }`}
        >
          QA Validation Suite ({testCases.length})
        </button>
      </div>

      {/* TAB 1: COMPLIANCE ISSUES */}
      {activeTab === "issues" && (
        <div className="space-y-4">
          {/* Filter Bar */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs">
            <div className="flex items-center gap-1.5">
              {(["all", "blocked", "warning", "passed"] as const).map((filter) => (
                <button
                  key={filter}
                  onClick={() => setIssueFilter(filter)}
                  className={`rounded-md px-2.5 py-1 font-medium capitalize transition cursor-pointer ${
                    issueFilter === filter ? "bg-primary text-primary-foreground" : "bg-accent text-muted-foreground hover:text-foreground"
                  }`}
                >
                  {filter}
                </button>
              ))}
            </div>
            <div className="relative">
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search issues, owners..."
                className="rounded-md border border-input bg-background px-3 py-1 text-xs text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary w-48"
              />
            </div>
          </div>

          {/* Issues List */}
          <div className="space-y-3">
            {filteredFindings.map((finding) => {
              const layman = explainComplianceFindingInLayman(finding);
              const isExpanded = showTechnicalDetails[finding.id];

              return (
                <div
                  key={finding.id}
                  className={`rounded-lg border p-4 space-y-2 transition ${
                    finding.status === "Blocked"
                      ? "border-rose-200 bg-rose-50/40"
                      : finding.status === "Warning"
                      ? "border-amber-200 bg-amber-50/40"
                      : "border-border bg-card"
                  }`}
                >
                  <div className="flex items-start justify-between gap-3">
                    <div className="space-y-0.5">
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-sm text-foreground">{layman.plainTitle}</span>
                        <span className="text-[10px] font-mono uppercase px-1.5 py-0.5 rounded bg-accent text-muted-foreground">
                          {layman.whoFixesIt}
                        </span>
                      </div>
                      <p className="text-xs text-foreground font-medium">{layman.whatWentWrong}</p>
                    </div>
                    <Badge tone={finding.status === "Passed" ? "success" : finding.status === "Blocked" ? "danger" : "warning"}>
                      {finding.status}
                    </Badge>
                  </div>

                  {/* Plain Language Action Required */}
                  {finding.status !== "Passed" && (
                    <div className="rounded bg-background p-2.5 text-xs text-foreground border border-border">
                      <strong className="text-primary">Action steps:</strong>
                      <ul className="list-disc list-inside mt-1 space-y-0.5 text-muted-foreground text-[11px]">
                        {layman.actionSteps.map((step, idx) => (
                          <li key={idx}>{step}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Technical Collapsible Details */}
                  <div className="pt-1">
                    <button
                      onClick={() => toggleTechnical(finding.id)}
                      className="text-[11px] font-semibold text-muted-foreground hover:text-foreground flex items-center gap-1 cursor-pointer"
                    >
                      {isExpanded ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
                      {isExpanded ? "Hide Technical / Store Rule Details" : "View Technical & Store Rule Details"}
                    </button>

                    {isExpanded && (
                      <div className="mt-2 rounded-md bg-accent/50 p-2.5 text-xs space-y-1 font-mono text-muted-foreground border border-border">
                        <p><strong>Original Title:</strong> {finding.title}</p>
                        <p><strong>Technical Detail:</strong> {finding.detail}</p>
                        {finding.guidelineRef && <p><strong>Guideline Ref:</strong> {finding.guidelineRef}</p>}
                        {finding.remediation && <p><strong>Engineering Remediation:</strong> {finding.remediation}</p>}
                        <p><strong>Assigned Owner:</strong> {finding.owner}</p>
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* TAB 2: PRE-SUBMISSION CHECKLIST */}
      {activeTab === "checklist" && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Department Pre-Flight Sign-Off Checklist</CardTitle>
            <p className="text-xs text-muted-foreground">
              Confirm these key milestones with respective functional owners prior to final submission.
            </p>
          </CardHeader>
          <CardContent className="space-y-3">
            {[
              { key: "legal", label: "Legal & Privacy: Public account deletion URL live and Data Safety form answers verified." },
              { key: "permissions", label: "Engineering: Target SDK 34+ set and high-risk background permissions justified." },
              { key: "qa", label: "QA Lead: Pre-flight test cases passed and automated smoke testing signed off." },
              { key: "storeAssets", label: "Marketing / PM: App Store screenshots and feature graphics meet guidelines." },
            ].map((item) => (
              <label key={item.key} className="flex items-start gap-3 rounded-lg border border-border p-3 hover:bg-accent/40 cursor-pointer select-none">
                <input
                  type="checkbox"
                  checked={checkedSignOffs[item.key] || false}
                  onChange={(e) => setCheckedSignOffs((prev) => ({ ...prev, [item.key]: e.target.checked }))}
                  className="mt-0.5 h-4 w-4 rounded border-input text-primary focus:ring-primary"
                />
                <span className="text-xs text-foreground font-medium">{item.label}</span>
              </label>
            ))}
          </CardContent>
        </Card>
      )}

      {/* TAB 3: PERMISSIONS */}
      {activeTab === "permissions" && (
        <div className="space-y-3">
          <div className="flex items-center justify-between text-xs text-muted-foreground">
            <p>Artifact: <strong>{manifest?.name || (project.platform === "iOS" ? "Info.plist" : "AndroidManifest.xml")}</strong></p>
            <p>Target SDK: <strong>{manifest?.targetSdkVersion ?? (project.platform === "iOS" ? 18 : 34)}</strong></p>
          </div>

          {(manifest?.permissions || []).map((perm) => {
            const layman = explainPermissionInLayman(perm);
            return (
              <div key={perm.name} className="rounded-lg border border-border bg-card p-3.5 space-y-1">
                <div className="flex items-center justify-between">
                  <div>
                    <span className="font-bold text-sm text-foreground">{layman.friendlyName}</span>
                    <span className="font-mono text-xs text-muted-foreground ml-2">({perm.name.split(".").pop()})</span>
                  </div>
                  <Badge tone={perm.risk === "High" ? "danger" : perm.risk === "Medium" ? "warning" : "success"}>
                    {perm.risk} Risk
                  </Badge>
                </div>
                <p className="text-xs text-muted-foreground">{layman.plainMeaning}</p>
                <p className="text-[11px] text-amber-700 font-medium"><strong>Store Policy Impact:</strong> {layman.storePolicyNotes}</p>
              </div>
            );
          })}
        </div>
      )}

      {/* TAB 4: PRIVACY POLICY */}
      {activeTab === "privacy" && (
        <div className="space-y-3">
          <div className="flex items-center justify-between text-xs text-muted-foreground">
            <p>Document: <strong>{privacyPolicy?.fileName || "Privacy Policy URL"}</strong></p>
          </div>

          {(privacyPolicy?.clauses || []).map((clause) => {
            const layman = explainPrivacyClauseInLayman(clause);
            return (
              <div key={clause.id} className="rounded-lg border border-border bg-card p-3.5 space-y-1">
                <div className="flex items-center justify-between">
                  <span className="font-bold text-sm text-foreground">{layman.plainTitle}</span>
                  <Badge tone={clause.status === "Passed" ? "success" : "warning"}>{clause.status}</Badge>
                </div>
                <p className="text-xs text-foreground">{layman.plainMeaning}</p>
                <p className="text-[11px] text-primary"><strong>PM Note:</strong> {layman.pmTakeaway}</p>
              </div>
            );
          })}
        </div>
      )}

      {/* TAB 5: QA TESTS */}
      {activeTab === "qa" && (
        <div className="space-y-2">
          {testCases.map((tc) => (
            <div key={tc.id} className="flex items-center justify-between rounded-lg border border-border bg-card p-3 text-xs">
              <div className="flex items-center gap-2">
                <CheckCircle2 className={`h-4 w-4 ${tc.status === "Passed" ? "text-emerald-600" : "text-amber-600"}`} />
                <span className="font-semibold text-foreground">{tc.title}</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-muted-foreground">{tc.area}</span>
                <Badge tone={tc.status === "Passed" ? "success" : "warning"}>{tc.status}</Badge>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Section 5: Official Auditor Sign-Off & Verification Status */}
      <Card className="border border-border">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-primary">
              <Fingerprint className="h-5 w-5" />
              <CardTitle>Auditor Certification &amp; Sign-Off</CardTitle>
            </div>
            {auditorSignature ? (
              <Badge tone="success">
                <ShieldCheck className="h-3.5 w-3.5 mr-1" /> Signed &amp; Certified
              </Badge>
            ) : (
              <Badge tone="warning">
                <Lock className="h-3.5 w-3.5 mr-1" /> Sign-Off Pending
              </Badge>
            )}
          </div>
        </CardHeader>
        <CardContent>
          {auditorSignature ? (
            <div className="rounded-lg border border-emerald-300 bg-emerald-50/40 p-4 space-y-2">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-emerald-200 pb-2">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-sm text-foreground">{auditorSignature.auditorName}</span>
                    <Badge tone="success" className="text-[10px]">Verified Auditor</Badge>
                  </div>
                  <p className="text-xs text-muted-foreground font-mono">
                    {auditorSignature.auditorRole} · ID: {auditorSignature.studentIdOrOrg}
                  </p>
                </div>
                <div className="text-left sm:text-right">
                  <p className="text-[11px] font-mono text-muted-foreground">
                    Signed: {new Date(auditorSignature.signedAt).toLocaleString()}
                  </p>
                  <p className="text-[10px] font-mono text-emerald-800 font-bold">
                    Hash: {auditorSignature.verificationHash}
                  </p>
                </div>
              </div>
              <p className="text-xs text-muted-foreground italic">
                &quot;I certify that I have reviewed all calculation steps, XML manifest checks, compliance validations, and QA test results for this release artifact.&quot;
              </p>
            </div>
          ) : (
            <div className="rounded-lg border border-dashed border-border bg-accent/30 p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div>
                <p className="text-xs font-semibold text-foreground">Formal Auditor Sign-Off Required</p>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Complete the anti-paste manual verification sign-off in the QA Verification Dossier.
                </p>
              </div>
              <Link to="/verification">
                <Button className="h-8 text-xs">
                  <UserCheck className="h-4 w-4 mr-1.5" /> Sign Dossier Now
                </Button>
              </Link>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Sign-off Footer */}
      <div className="rounded-lg border border-border bg-card p-5 text-xs text-muted-foreground flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <p>© 2026 ReleaseIQ Quality Assurance Engine. Pre-flight verification certificate.</p>
        <p className="font-mono">Audit Hash: {project.id.slice(0, 8)}-{Date.now().toString(36).toUpperCase()}</p>
      </div>
    </div>
  );
}
